### ISSUE TITLE
[TRACKER] More unit tests

### ISSUE THREAD

**Issue by SIMULATAN** [Black0nion/BlackOnion-Bot#172]
More tests would help make the base safer.

Checklist of whats left to implement:
- [ ] OAuth2
- [ ] API endpoints
	- [ ] paths
	- [x] whoami (mocking)

Please add more ideas for tests, the more that's tested the safer it is!

**Comment by RealYusufIsmail** [comment]
Regarding the test have a look at TJ bots unit test. Like how they do it. I asked them and they said 
![image](https://user-images.githubusercontent.com/67903886/167806503-5790ae91-c941-4c67-b086-48b5c2074a1b.png)
