### ISSUE TITLE
[FEATURE REQUEST] Introduced TIme out command

### ISSUE THREAD

**Issue by RealYusufIsmail** [Black0nion/BlackOnion-Bot#185]
**Is your feature request related to a problem? Please describe.**
As seen with introduction of the time out in discord you can only set only a certain amount of time when using the timeout feature on Discord meaning if we introduced a system were give the user the ability to set a custom amount(max is 28 days)

**Comment by SIMULATAN** [comment]
Good idea, if you want to, you can implement it yourself and make a PR

**Comment by RealYusufIsmail** [comment]
> Good idea, if you want to, you can implement it yourself and make a PR

I was planning it.
