### ISSUE TITLE
[FEATURE REQUEST] Introduce Logger system

### ISSUE THREAD

**Issue by RealYusufIsmail** [Black0nion/BlackOnion-Bot#186]
**Is your feature request related to a problem? Please describe.**
Instead of using System.out.println a logger should be used as this is a major bug and as said by Sonar lint 
```
"If a program directly writes to the standard outputs, there is absolutely no way to comply with those requirements. That’s why defining and using a dedicated logger is highly recommended."
```
**Describe the solution you'd like**
Introduced a logger system and replace all the System.out.println

**Comment by SIMULATAN** [comment]
I already use logback? Theoretically, the only sysout calls are from minor old legacy code

**Comment by RealYusufIsmail** [comment]
> I already use logback? Theoretically, the only sysout calls are from minor old legacy code

oh ok then the legacy code should be chaned.

**Comment by SIMULATAN** [comment]
Agreed, that's why we currently work so hard on migrating things. If you see any sysout call, please replace it with the SLF4J version (`LoggerFactory.getLogger(MyClass.class)`)

**Comment by RealYusufIsmail** [comment]
ok
